### ISSUE TITLE
Update/remove by line

### ISSUE THREAD

**Issue by oscarstranger** [Elkfox/Cartfox#14]
We should be updating and removing items `by line` _by default_, instead of by `variant id`. This addresses issues with conflicts once item properties come into play.

**Comment by cam** [comment]
@oscarstranger let's bring those extra functions from Merchline into Elkfox Cart too. I think they will prove useful for anyone developing themes for Plus merchants.

**Comment by oscarstranger** [comment]
@Cam Remove by line now the default on CF 3x 🛒 🦊
